name: memory_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  excel: ^2.1.0
  fl_chart: ^0.64.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  go_router: ^11.1.4
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/animalspics/
    - assets/geometrics/
    - assets/home/
    - assets/profesions/
    - assets/toys/
    - assets/transports/
